name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: fabacab/jekyll-builder-for-github-pages-action@master
      with:
        # Provide this action with your repository's `GH_PAGES_TOKEN`
        # "Secret" variable. This should be the value of a personal
        # access token granted, at a minimum, the `public_repo` and
        # the `repo_deployment` scopes needed to deploy to GH Pages.
        secret_gh_pages_api_token: ${{ secrets.SECRET }}
    # - name: Set up Ruby 2.6
    #   uses: actions/setup-ruby@v1
    #   with:
    #     ruby-version: 2.6.x
    # - name: Bundle install
    #   run: |
    #     bundle config path vendor/bundle
    #     bundle install --jobs 4 --retry 3
    # - name: Build with Jekyll
    #   run: |
    #     bundle exec jekyll build
